defaults:
  time_id: "zenduretime"
  name: "Hyper2000"
  id: "hyper_2000"
  watt_limit: "1200"
  # mac_address: ""

external_components:
  - source: github://danez/esphome-zendure-bridge@1.0.7
    components: [ zendure ]

esphome:
  min_version: "2025.4.1"

json:

zendure:

esp32_ble_tracker:

globals:
  - id: "${id}_device_id"
    type: std::string
    restore_value: no
    initial_value: '""'
  - id: "${id}_batteries"
    type: "battery_handler_map_t"
    restore_value: no

interval:
  - interval: 1min
    startup_delay: 75s
    then:
      - !include
        file: includes/ble-get-info.yaml
        vars:
          device_id: "${id}"
          time_id: "${time_id}"
      - !include
        file: includes/ble-get-all.yaml
        vars:
          device_id: "${id}"
          time_id: "${time_id}"

ble_client:
  - mac_address: ${mac_address}
    id: "zendure_ble_${id}"
    on_connect:
      then:
        - esp32_ble_tracker.stop_scan:
        - delay: 5s
        - wait_until:
            condition:
              time.has_time:
        - !include
          file: includes/ble-get-info.yaml
          vars:
            device_id: "${id}"
            time_id: "${time_id}"
        - !include
          file: includes/ble-get-all.yaml
          vars:
            device_id: "${id}"
            time_id: "${time_id}"
    on_disconnect:
      then:
        - esp32_ble_tracker.start_scan:
            continuous: true

text_sensor:
  - platform: ble_client
    id: "zendure_ble_receiver_${id}"
    ble_client_id: "zendure_ble_${id}"
    internal: true
    service_uuid: a002
    characteristic_uuid: c305
    notify: true
    update_interval: never
    on_notify:
      then:
        - lambda: |-
            static const sensor_handler_map_t property_handlers = {
              {"reverseState", [](int value) { publish_state_if_changed(id(${id}_reverseState), !!value); }},
              {"gridReverse", [](int value) { publish_state_if_changed(id(${id}_gridReverse), value); }},
              {"gridInputPower", [](int value) { publish_state_if_changed(id(${id}_gridInputPower), value); }},
              {"heatState", [](int value) { publish_state_if_changed(id(${id}_heatState), !!value); }},
              {"ambientSwitch", [](int value) { publish_state_if_changed(id(${id}_ambientSwitch), !!value); }},
              {"lampSwitch", [](int value) { publish_state_if_changed(id(${id}_lampSwitchSensor), !!value); }},  # Remplacé lampSwitch par lampSwitchSensor
              {"autoHeat", [](int value) { publish_state_if_changed(id(${id}_autoHeat), !!value); }},
              {"ctOff", [](int value) { publish_state_if_changed(id(${id}_ctOff), !!value); }},
              {"inputLimit", [](int value) { publish_state_if_changed(id(${id}_inputLimit), value); }},
              {"hubState", [](int value) { publish_state_if_changed(id(${id}_hubState), value); }},
              {"gridOffMode", [](int value) { publish_state_if_changed(id(${id}_gridOffMode), value); }},
              {"outputHomePower", [](int value) { publish_state_if_changed(id(${id}_outputHomePower), value); }},
              {"solarPower1", [](int value) { publish_state_if_changed(id(${id}_solarPower1), value); }},
              {"solarPower2", [](int value) { publish_state_if_changed(id(${id}_solarPower2), value); }},
              {"solarInputPower", [](int value) { publish_state_if_changed(id(${id}_solarInputPower), value); }},
              {"outputPackPower", [](int value) { publish_state_if_changed(id(${id}_outputPackPower), value); }},
              {"electricLevel", [](int value) { publish_state_if_changed(id(${id}_electricLevel), value); }},
              {"packInputPower", [](int value) { publish_state_if_changed(id(${id}_packInputPower), value); }},
              {"packNum", [](int value) { publish_state_if_changed(id(${id}_packNum), value); }},
              {"remainOutTime", [](int value) { publish_state_if_changed(id(${id}_remainOutTime), value / TIME_HOURS_SCALE); }},
              {"remainInputTime", [](int value) { publish_state_if_changed(id(${id}_remainInputTime), value / TIME_HOURS_SCALE); }},
              {"pass", [](int value) { publish_state_if_changed(id(${id}_pass), !!value); }},
              {"outputLimit", [](int value) { publish_state_if_changed(id(${id}_outputLimit), value); }},
              {"socSet", [](int value) { publish_state_if_changed(id(${id}_socSet), value / PERCENT_SCALE); }},
              {"minSoc", [](int value) { publish_state_if_changed(id(${id}_minSoc), value / PERCENT_SCALE); }},
              {"buzzerSwitch", [](int value) { publish_state_if_changed(id(${id}_buzzerSwitch), !!value); }},
              {"masterSwitch", [](int value) { publish_state_if_changed(id(${id}_masterSwitch), !!value); }}
            };
            json::parse_json(x, [](JsonObject root) -> bool {
              handle_device_message(
                root,
                property_handlers,
                id(${id}_batteries),
                id(${id}_device_id),
                "${id}"
              );
              return true;
            });

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: "zendure_ble_${id}"
    update_interval: 60s
    name: "${name} RSSI"
    entity_category: diagnostic
    disabled_by_default: true

  - platform: template
    name: "${name} Grid Input Power"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    id: "${id}_gridInputPower"

  - platform: template
    name: "${name} Output Home Power"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    id: "${id}_outputHomePower"

  - platform: template
    name: "${name} Solar Power 1"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    id: "${id}_solarPower1"

  - platform: template
    name: "${name} Solar Power 2"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    id: "${id}_solarPower2"

  - platform: template
    name: "${name} Solar Input Power"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    id: "${id}_solarInputPower"

  - platform: template
    name: "${name} Output Pack Power"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    id: "${id}_outputPackPower"

  - platform: template
    name: "${name} Electricity Level"
    device_class: battery
    state_class: measurement
    unit_of_measurement: "%"
    id: "${id}_electricLevel"

  - platform: template
    name: "${name} Pack Input Power"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    id: "${id}_packInputPower"

  - platform: template
    name: "${name} Remain Out Time"
    device_class: duration
    state_class: measurement
    unit_of_measurement: "h"
    accuracy_decimals: 2
    id: "${id}_remainOutTime"

  - platform: template
    name: "${name} Remain Input Time"
    device_class: duration
    state_class: measurement
    unit_of_measurement: "h"
    accuracy_decimals: 2
    id: "${id}_remainInputTime"

  - platform: template
    name: "${name} Pack Num"
    entity_category: diagnostic
    disabled_by_default: true
    id: "${id}_packNum"

  - platform: template
    name: "${name} Grid Off Mode"    # Ajout du sensor manquant
    id: "${id}_gridOffMode"

number:
  - platform: template
    name: "${name} Soc Set"
    mode: slider
    id: "${id}_socSet"
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      - !include
        file: includes/ble-set-property.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: socSet

  - platform: template
    name: "${name} Min Soc"
    mode: slider
    id: "${id}_minSoc"
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      - !include
        file: includes/ble-set-property.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: minSoc

  - platform: template
    name: "${name} Output Limit"
    mode: slider
    id: "${id}_outputLimit"
    unit_of_measurement: "W"
    min_value: 0
    max_value: ${watt_limit}
    step: 1
    optimistic: true
    set_action:
      - !include
        file: includes/ble-set-property.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: outputLimit

  - platform: template
    name: "${name} Input Limit"
    mode: slider
    id: "${id}_inputLimit"
    unit_of_measurement: "W"
    min_value: 0
    max_value: 1200
    step: 1
    optimistic: true
    set_action:
      - !include
        file: includes/ble-set-property.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: inputLimit

binary_sensor:
  - platform: template
    name: "${name} Reverse State"
    id: "${id}_reverseState"
  - platform: template
    id: "${id}_heatState"
    name: "${name} Heat State"
  - platform: template
    id: "${id}_ambientSwitch"
    name: "${name} Ambient Switch"
  - platform: template
    id: "${id}_lampSwitchSensor"    # Renommé par sécurité, évite conflit avec switch
    name: "${name} Lamp Switch State"
  - platform: template
    id: "${id}_autoHeat"
    name: "${name} Auto Heat"
  - platform: template
    id: "${id}_ctOff"
    name: "${name} CT Off"

switch:
  - platform: template
    name: "${name} Lamp Switch"
    id: "${id}_lampSwitch"
    optimistic: true
    icon: mdi:lightbulb
    turn_on_action:
      - !include
        file: includes/ble-set-property-value.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: lampSwitch
          value: 1
    turn_off_action:
      - !include
        file: includes/ble-set-property-value.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: lampSwitch
          value: 0

  - platform: template
    name: "${name} Buzzer Switch"
    id: "${id}_buzzerSwitch"
    optimistic: true
    icon: mdi:volume-high
    turn_on_action:
      - !include
        file: includes/ble-set-property-value.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: buzzerSwitch
          value: 1
    turn_off_action:
      - !include
        file: includes/ble-set-property-value.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: buzzerSwitch
          value: 0

  - platform: template
    name: "${name} Auto Recover"
    id: "${id}_autoRecover"
    optimistic: true
    icon: mdi:restore
    turn_on_action:
      - !include
        file: includes/ble-set-property-value.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: autoRecover
          value: 1
    turn_off_action:
      - !include
        file: includes/ble-set-property-value.yaml
        vars:
          time_id: "${time_id}"
          device_id: "${id}"
          key: autoRecover
          value: 0

  - platform: template
    name: "${name} Master Switch"
    id: "${id}_masterSwitch"
    optimistic: true
    icon: mdi:power

select:
  - platform: template
    name: "${name} Grid Reverse"
    id: "${id}_gridReverse"
    options:
      - "auto"
      - "on"
      - "off"
    optimistic: true
    restore_value: true
    set_action:
      - ble_client.ble_write:
          id: "zendure_ble_${id}"
          service_uuid: a002
          characteristic_uuid: c304
          value: !lambda |-
            char buffer[120];
            int timestamp = (int) id(${time_id}).now().timestamp;
            int propValue = x == "auto" ? 0 : (x == "on" ? 1 : 2);
            snprintf(buffer, sizeof(buffer), "{\"method\":\"write\",\"timestamp\":\"%d\",\"messageId\":\"none\",\"deviceId\":\"%s\",\"properties\":{\"gridReverse\":%d}}", timestamp, id(${id}_device_id).c_str(), propValue);
            std::vector<uint8_t> value(buffer, buffer + strlen(buffer));
            ESP_LOGD("${id}", "Sending Command '%s'", buffer);
            return value

  - platform: template
    name: "${name} Hub State"
    id: "${id}_hubState"
    icon: mdi:power-settings
    options:
      - "Standby"
      - "Shut Down"
    optimistic: true
    restore_value: true
    set_action:
      - ble_client.ble_write:
          id: "zendure_ble_${id}"
          service_uuid: a002
          characteristic_uuid: c304
          value: !lambda |-
            char buffer[120];
            int timestamp = (int) id(${time_id}).now().timestamp;
            int propValue = x == "Standby" ? 0 : 1;
            snprintf(buffer, sizeof(buffer), "{\"method\":\"write\",\"timestamp\":\"%d\",\"messageId\":\"none\",\"deviceId\":\"%s\",\"properties\":{\"hubState\":%d}}", timestamp, id(${id}_device_id).c_str(), propValue);
            std::vector<uint8_t> value(buffer, buffer + strlen(buffer));
            ESP_LOGD("${id}", "Sending Command '%s'", buffer);
            return value
